version: "2"
services:
  app:
    build: .
    links:
      - db
    ports:
      - "5000:80"
    depends_on:
      - db
    networks:
      - test
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql
    networks:
      - test
networks:
  test: